{\rtf1\ansi\ansicpg936\deff0\deflang1033\deflangfe2052{\fonttbl{\f0\fmodern Consolas;}{\f1\fnil\fcharset129 Courier New;}}
{\colortbl ;\red20\green20\blue20;\red142\green142\blue142;\red94\green147\blue162;}
\viewkind4\uc1\pard\lang2052\f0\fs20 [root@devserver-hps-a0f74d4d-g00615224-00027 d0]# tail -f server_0.log\cf1\highlight2 
\par \cf0\highlight0     self.engine_core = core_client_class(\cf1\highlight2 
\par \cf0\highlight0                        ^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core_client.py", line 781, in __init__\cf1\highlight2 
\par \cf0\highlight0     super().__init__(\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core_client.py", line 425, in __init__\cf1\highlight2 
\par \cf0\highlight0     self._wait_for_engine_startup(output_address, parallel_config)\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core_client.py", line 494, in _wait_for_engine_startup\cf1\highlight2 
\par \cf0\highlight0     raise RuntimeError("Engine core initialization failed. "\cf1\highlight2 
\par \cf0\highlight0 RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): \{\}\cf1\highlight2 
\par \cf0\highlight0 [ERROR] 2025-10-24-17:55:03 (PID:130631, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception\cf1\highlight2 
\par \cf0\highlight0 ^C\cf1\highlight2 
\par \cf0\highlight0 [root@devserver-hps-a0f74d4d-g00615224-00027 d0]# tail -f server_0.log\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:34 [loader.py:312] prefill_nodes_num loads from vllm config: 1\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:34 [loader.py:312] decode_nodes_num loads from vllm config: 1\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:34 [loader.py:312] enable_chunked_prefill loads from vllm config: True\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:34 [loader.py:312] enable_omni_placement loads from vllm config: False\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:34 [loader.py:312] decode_gear_list loads from vllm config: [4]\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:34 [loader.py:312] enable_graph_mode loads from vllm config: False\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:34 [loader.py:265] The task about longcat-flash_bf16_A3 load configuration file from /data/00943438/run_dir/omniinfer/omni/models/configs/longcat_decode_bf16_1p1d.json\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  WARNING 10-24 18:04:34 [loader.py:299] [WARNING] Eager mode disables all these optimization configurations by default.\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:34 [loader.py:31] Task config updated via 'update_task_config'\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:34 [parallel_state.py:933] Adjusting world_size=64 rank=0 distributed_init_method=tcp://7.150.12.42:7165 for DP\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:40 [parallel_state.py:1064] rank 0 in world size 64 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:40 [shm_broadcast.py:250] vLLM message queue communication handle: Handle(local_reader_ranks=[1, 2, 3], buffer_handle=(3, 4194304, 6, 'psm_177118be'), local_subscribe_addr='ipc:///tmp/a53fde3e-c447-42e0-ae6e-02c84876beff', remote_subscribe_addr=None, remote_addr_ipv6=False)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:40 [shm_broadcast.py:250] vLLM message queue communication handle: Handle(local_reader_ranks=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], buffer_handle=(15, 4194304, 6, 'psm_b4581370'), local_subscribe_addr='ipc:///tmp/e369dc67-7de8-4ecf-8881-400e31c9e4f0', remote_subscribe_addr=None, remote_addr_ipv6=False)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:40 [factory.py:73] Creating v1 connector with name: AscendHcclConnectorV1\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:40 [llmdatadist_connector_v1.py:114] Set kv_parallel_size to 1 when use deepseek mla model.\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:40 [npu_model_runner.py:1024] Starting to load model /data/models/LongCat-Flash...\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:   0% Completed | 0/75 [00:00<?, ?it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:   1% Completed | 1/75 [00:00<00:10,  7.38it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:   3% Completed | 2/75 [00:00<00:09,  8.02it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:   5% Completed | 4/75 [00:00<00:07,  9.16it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:   7% Completed | 5/75 [00:00<00:07,  9.19it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:   8% Completed | 6/75 [00:00<00:07,  9.37it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:   9% Completed | 7/75 [00:00<00:07,  9.29it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  11% Completed | 8/75 [00:00<00:07,  9.17it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  12% Completed | 9/75 [00:01<00:07,  8.40it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  13% Completed | 10/75 [00:01<00:07,  8.45it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  15% Completed | 11/75 [00:01<00:07,  8.73it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  16% Completed | 12/75 [00:01<00:07,  8.60it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  17% Completed | 13/75 [00:01<00:07,  8.55it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  19% Completed | 14/75 [00:01<00:07,  8.44it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  20% Completed | 15/75 [00:01<00:07,  8.57it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  23% Completed | 17/75 [00:01<00:05, 11.01it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  25% Completed | 19/75 [00:02<00:05, 10.08it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  28% Completed | 21/75 [00:02<00:05,  9.63it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  29% Completed | 22/75 [00:02<00:05,  9.44it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  31% Completed | 23/75 [00:02<00:05,  9.31it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  32% Completed | 24/75 [00:02<00:05,  9.05it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  33% Completed | 25/75 [00:02<00:05,  8.94it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  35% Completed | 26/75 [00:02<00:05,  8.76it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  36% Completed | 27/75 [00:02<00:05,  8.58it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  37% Completed | 28/75 [00:03<00:05,  8.53it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  39% Completed | 29/75 [00:03<00:05,  8.45it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  40% Completed | 30/75 [00:03<00:05,  8.39it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  41% Completed | 31/75 [00:03<00:05,  8.69it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  43% Completed | 32/75 [00:03<00:04,  8.73it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  44% Completed | 33/75 [00:03<00:05,  8.25it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  45% Completed | 34/75 [00:03<00:05,  7.98it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  47% Completed | 35/75 [00:03<00:04,  8.27it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  51% Completed | 38/75 [00:04<00:02, 13.68it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  53% Completed | 40/75 [00:04<00:03, 11.43it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  56% Completed | 42/75 [00:04<00:03, 10.52it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  59% Completed | 44/75 [00:04<00:03,  9.93it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  61% Completed | 46/75 [00:04<00:03,  9.43it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  64% Completed | 48/75 [00:05<00:02,  9.24it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  65% Completed | 49/75 [00:05<00:02,  9.13it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  67% Completed | 50/75 [00:05<00:02,  9.00it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  68% Completed | 51/75 [00:05<00:02,  9.00it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  69% Completed | 52/75 [00:05<00:02,  8.84it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  71% Completed | 53/75 [00:05<00:02,  8.87it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  72% Completed | 54/75 [00:05<00:02,  8.98it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  73% Completed | 55/75 [00:05<00:02,  8.90it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  75% Completed | 56/75 [00:06<00:02,  9.03it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  76% Completed | 57/75 [00:06<00:02,  8.85it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  77% Completed | 58/75 [00:06<00:01,  9.10it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  79% Completed | 59/75 [00:06<00:01,  9.21it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  80% Completed | 60/75 [00:06<00:01,  9.38it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  81% Completed | 61/75 [00:06<00:01,  9.35it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  83% Completed | 62/75 [00:06<00:01,  9.17it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  84% Completed | 63/75 [00:06<00:01,  9.05it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  85% Completed | 64/75 [00:06<00:01,  8.90it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  87% Completed | 65/75 [00:07<00:01,  8.90it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  88% Completed | 66/75 [00:07<00:00,  9.07it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  89% Completed | 67/75 [00:07<00:00,  9.02it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  91% Completed | 68/75 [00:07<00:00,  9.02it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  92% Completed | 69/75 [00:07<00:00,  9.14it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  95% Completed | 71/75 [00:07<00:00,  9.31it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  96% Completed | 72/75 [00:07<00:00,  9.08it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards:  97% Completed | 73/75 [00:07<00:00,  8.89it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards: 100% Completed | 75/75 [00:08<00:00, 11.31it/s]\cf1\highlight2 
\par \cf0\highlight0 Loading safetensors checkpoint shards: 100% Completed | 75/75 [00:08<00:00,  9.27it/s]\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:49 [default_loader.py:280] Loading weights took 8.14 seconds\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  INFO 10-24 18:04:50 [npu_model_runner.py:1036] Loading model weights took 30.3016 GB\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623] EngineCore failed to start.\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623] Traceback (most recent call last):\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 612, in run_engine_core\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     engine_core = DPEngineCoreProc(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 854, in __init__\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     super().__init__(vllm_config, on_head_node, input_address,\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 506, in __init__\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     super().__init__(vllm_config, executor_class, log_stats,\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 90, in __init__\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     self._initialize_kv_caches(vllm_config)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 183, in _initialize_kv_caches\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     available_gpu_memory = self.model_executor.determine_available_memory()\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/executor/abstract.py", line 75, in determine_available_memory\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     output = self.collective_rpc("determine_available_memory")\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/executor/uniproc_executor.py", line 56, in collective_rpc\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     answer = run_method(self.driver_worker, method, args, kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/utils.py", line 2605, in run_method\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return func(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/worker/npu_worker.py", line 227, in determine_available_memory\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     cur_npu_kv_cache_bytes = self._compute_kv_cache_bytes()\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/worker/npu_worker.py", line 281, in _compute_kv_cache_bytes\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     self.model_runner.profile_run()\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/worker/npu_model_runner.py", line 1012, in profile_run\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     hidden_states = self._dummy_run(self.max_batch_size * get_dp_group().world_size)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/usr/local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return func(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/worker/npu_model_runner.py", line 915, in _dummy_run\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     forward_results = self.model(\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]                       ^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/compilation/wrapper.py", line 94, in __call__\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return self.call_dispatcher(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/compilation/wrapper.py", line 65, in call_dispatcher\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return self.forward(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_flash.py", line 339, in forward\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     hidden_states = self.model(input_ids, positions, kv_caches,\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return self._call_impl(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return forward_call(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_flash.py", line 277, in forward\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     hidden_states, residual = layer(positions,\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]                               ^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return self._call_impl(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return forward_call(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_flash.py", line 181, in forward\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     moe_hidden_states = self.mlp(moe_hidden_states, attn_metadata)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return self._call_impl(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return forward_call(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_moe.py", line 262, in forward\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     return self._forward_prefill_norm(hidden_states, attn_metadata)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_moe.py", line 281, in _forward_prefill_norm\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     topk_weights, topk_ids = self.router.get_topk_indices(router_logits)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]   File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_moe.py", line 111, in get_topk_indices\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]     scores_for_choice = scores.view(-1, n_routed_experts) + self.e_score_correction_bias.unsqueeze(0)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623]                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  ERROR 10-24 18:04:55 [core.py:623] AttributeError: 'NoneType' object has no attribute 'unsqueeze'\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  Process EngineCore_0:\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  Traceback (most recent call last):\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      self.run()\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      self._target(*self._args, **self._kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 627, in run_engine_core\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      raise e\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 612, in run_engine_core\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      engine_core = DPEngineCoreProc(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 854, in __init__\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      super().__init__(vllm_config, on_head_node, input_address,\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 506, in __init__\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      super().__init__(vllm_config, executor_class, log_stats,\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 90, in __init__\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      self._initialize_kv_caches(vllm_config)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core.py", line 183, in _initialize_kv_caches\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      available_gpu_memory = self.model_executor.determine_available_memory()\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/executor/abstract.py", line 75, in determine_available_memory\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      output = self.collective_rpc("determine_available_memory")\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/executor/uniproc_executor.py", line 56, in collective_rpc\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      answer = run_method(self.driver_worker, method, args, kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/utils.py", line 2605, in run_method\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return func(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/worker/npu_worker.py", line 227, in determine_available_memory\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      cur_npu_kv_cache_bytes = self._compute_kv_cache_bytes()\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/worker/npu_worker.py", line 281, in _compute_kv_cache_bytes\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      self.model_runner.profile_run()\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/worker/npu_model_runner.py", line 1012, in profile_run\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      hidden_states = self._dummy_run(self.max_batch_size * get_dp_group().world_size)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/usr/local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return func(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/worker/npu_model_runner.py", line 915, in _dummy_run\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      forward_results = self.model(\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0                        ^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/compilation/wrapper.py", line 94, in __call__\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return self.call_dispatcher(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/adaptors/vllm/compilation/wrapper.py", line 65, in call_dispatcher\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return self.forward(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_flash.py", line 339, in forward\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      hidden_states = self.model(input_ids, positions, kv_caches,\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return self._call_impl(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return forward_call(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_flash.py", line 277, in forward\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      hidden_states, residual = layer(positions,\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0                                ^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return self._call_impl(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return forward_call(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_flash.py", line 181, in forward\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      moe_hidden_states = self.mlp(moe_hidden_states, attn_metadata)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return self._call_impl(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return forward_call(*args, **kwargs)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_moe.py", line 262, in forward\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      return self._forward_prefill_norm(hidden_states, attn_metadata)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_moe.py", line 281, in _forward_prefill_norm\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      topk_weights, topk_ids = self.router.get_topk_indices(router_logits)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0    File "/data/00943438/run_dir/omniinfer/omni/models/longcat/longcat_moe.py", line 111, in get_topk_indices\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0      scores_for_choice = scores.view(-1, n_routed_experts) + self.e_score_correction_bias.unsqueeze(0)\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf3\highlight0 (EngineCore_0 pid=144822)\cf0  AttributeError: 'NoneType' object has no attribute 'unsqueeze'\cf1\highlight2 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight2 
\par \cf0\highlight0   File "/usr/local/bin/vllm", line 8, in <module>\cf1\highlight2 
\par \cf0\highlight0     sys.exit(main())\cf1\highlight2 
\par \cf0\highlight0              ^^^^^^\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/entrypoints/cli/main.py", line 56, in main\cf1\highlight2 
\par \cf0\highlight0     args.dispatch_function(args)\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/entrypoints/cli/serve.py", line 42, in cmd\cf1\highlight2 
\par \cf0\highlight0 /usr/local/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 2 leaked shared_memory objects to clean up at shutdown\cf1\highlight2 
\par \cf0\highlight0   warnings.warn('resource_tracker: There appear to be %d '\cf1\highlight2 
\par \cf0\highlight0     uvloop.run(run_server(args))\cf1\highlight2 
\par \cf0\highlight0   File "/usr/local/lib/python3.11/site-packages/uvloop/__init__.py", line 105, in run\cf1\highlight2 
\par \cf0\highlight0     return runner.run(wrapper())\cf1\highlight2 
\par \cf0\highlight0            ^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf0\highlight0   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run\cf1\highlight2 
\par \cf0\highlight0     return self._loop.run_until_complete(task)\cf1\highlight2 
\par \cf0\highlight0            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf0\highlight0   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete\cf1\highlight2 
\par \cf0\highlight0   File "/usr/local/lib/python3.11/site-packages/uvloop/__init__.py", line 61, in wrapper\cf1\highlight2 
\par \cf0\highlight0     return await main\cf1\highlight2 
\par \cf0\highlight0            ^^^^^^^^^^\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/entrypoints/openai/api_server.py", line 1405, in run_server\cf1\highlight2 
\par \cf0\highlight0     async with build_async_engine_client(args) as engine_client:\cf1\highlight2 
\par \cf0\highlight0   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__\cf1\highlight2 
\par \cf0\highlight0     return await anext(self.gen)\cf1\highlight2 
\par \cf0\highlight0            ^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/entrypoints/openai/api_server.py", line 155, in build_async_engine_client\cf1\highlight2 
\par \cf0\highlight0     async with build_async_engine_client_from_engine_args(\cf1\highlight2 
\par \cf0\highlight0   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__\cf1\highlight2 
\par \cf0\highlight0     return await anext(self.gen)\cf1\highlight2 
\par \cf0\highlight0            ^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/entrypoints/openai/api_server.py", line 187, in build_async_engine_client_from_engine_args\cf1\highlight2 
\par \cf0\highlight0     async_llm = AsyncLLM.from_vllm_config(\cf1\highlight2 
\par \cf0\highlight0                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/async_llm.py", line 158, in from_vllm_config\cf1\highlight2 
\par \cf0\highlight0     return cls(\cf1\highlight2 
\par \cf0\highlight0            ^^^^\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/async_llm.py", line 117, in __init__\cf1\highlight2 
\par \cf0\highlight0     self.engine_core = core_client_class(\cf1\highlight2 
\par \cf0\highlight0                        ^^^^^^^^^^^^^^^^^^\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core_client.py", line 781, in __init__\cf1\highlight2 
\par \cf0\highlight0     super().__init__(\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core_client.py", line 425, in __init__\cf1\highlight2 
\par \cf0\highlight0     self._wait_for_engine_startup(output_address, parallel_config)\cf1\highlight2 
\par \cf0\highlight0   File "/data/00943438/run_dir/omniinfer/infer_engines/vllm/vllm/v1/engine/core_client.py", line 494, in _wait_for_engine_startup\cf1\highlight2 
\par \cf0\highlight0     raise RuntimeError("Engine core initialization failed. "\cf1\highlight2 
\par \cf0\highlight0 RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): \{\}\cf1\highlight2 
\par \cf0\highlight0 [ERROR] 2025-10-24-18:04:56 (PID:140304, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception\cf1\highlight2 
\par \pard\cf0\highlight0\f1 
\par }
 